debug

diff --git a/.github/workflows/autobuild.yml b/.github/workflows/autobuild.yml
--- a/.github/workflows/autobuild.yml
+++ b/.github/workflows/autobuild.yml
@@ -15,23 +15,23 @@ jobs:
     name: Windows
     runs-on: windows-latest
     steps:
-      - uses: benjlevesque/short-sha@v2.2
-        id: short-sha
-        with:
-          length: 7
+      # - uses: benjlevesque/short-sha@v2.2
+      #   id: short-sha
+      #   with:
+      #     length: 7
 
-      - uses: msys2/setup-msys2@v2
-        with:
-          msystem: mingw64
-          install: >-
-            base-devel
-            git
-            ruby
-            vim
-            mingw-w64-x86_64-cmake
-            mingw-w64-x86_64-meson
-            mingw-w64-x86_64-autotools
-            mingw-w64-x86_64-gcc
+      # - uses: msys2/setup-msys2@v2
+      #   with:
+      #     msystem: mingw64
+      #     install: >-
+      #       base-devel
+      #       git
+      #       ruby
+      #       vim
+      #       mingw-w64-x86_64-cmake
+      #       mingw-w64-x86_64-meson
+      #       mingw-w64-x86_64-autotools
+      #       mingw-w64-x86_64-gcc
 
       - name: Checkout private steam sdk repo
         uses: actions/checkout@v4
@@ -39,84 +39,88 @@ jobs:
           repository: ${{ secrets.STEAM_SDK_REPO }}    # owner/repo
           token: ${{ secrets.STEAM_SDK_TOKEN }}        # PAT stored as secret
           path: steam_sdk
+       run: |
+         tree . -d
+         ls steam_sdk/redistributable_bin/win64
+         ls steam_sdk/
       
-      - name: Checkout repository
-        uses: actions/checkout@v5
+      # - name: Checkout repository
+      #   uses: actions/checkout@v5
 
-      - uses: actions/cache@v4
-        with:
-          path: |
-            windows/build-mingw64
-            windows/downloads
-          key: win-${{ hashFiles('windows/Makefile') }}
+      # - uses: actions/cache@v4
+      #   with:
+      #     path: |
+      #       windows/build-mingw64
+      #       windows/downloads
+      #     key: win-${{ hashFiles('windows/Makefile') }}
 
-      - name: Build all dependencies
-        shell: msys2 {0}
-        run: |
-          cd windows
-          make
+      # - name: Build all dependencies
+      #   shell: msys2 {0}
+      #   run: |
+      #     cd windows
+      #     make
 
-      - name: Build exe
-        env:
-          STEAMWORKS_PATH: "${{ github.workspace }}\\steam_sdk"
-          STEAM_APPID: "${{ secrets.STEAM_APPID }}"
-        shell: msys2 {0}
-        run: |
-          source windows/vars.sh
-          STEAM_PATH=$(cygpath -u "$STEAMWORKS_PATH")
-          meson setup build -Duse_miniffi=true -Dsteamworks_path="$STEAM_PATH" -Dsteam_appid="$STEAM_APPID"
-          cd build
-          ninja
-          strip ./mkxp-z.exe
-          strip ./steam_mkxp-z.exe
+      # - name: Build exe
+      #   env:
+      #     STEAMWORKS_PATH: "${{ github.workspace }}\\steam_sdk"
+      #     STEAM_APPID: "${{ secrets.STEAM_APPID }}"
+      #   shell: msys2 {0}
+      #   run: |
+      #     source windows/vars.sh
+      #     STEAM_PATH=$(cygpath -u "$STEAMWORKS_PATH")
+      #     meson setup build -Duse_miniffi=true -Dsteamworks_path="$STEAM_PATH" -Dsteam_appid="$STEAM_APPID"
+      #     cd build
+      #     ninja
+      #     strip ./mkxp-z.exe
+      #     strip ./steam_mkxp-z.exe
 
 
-      - name: Prepare archive
-        shell: msys2 {0}
-        run: |
-          mkdir build/artifact
-          cd build/artifact
-          cp /mingw64/bin/zlib1.dll .
-          cp ../../windows/build-mingw64/bin/x64-msvcrt-ruby310.dll .
-          cp -r ../../windows/build-mingw64/lib/ruby/3.1.0 .
-          mv ./3.1.0 ./stdlib
-          cp ../mkxp-z.exe .
-          cp ../steam_mkxp-z.exe .
-          cp $STEAMWORKS_PATH/redistributable_bin/win64/steam_api64.dll .
-          cp ../../mkxp.json .
-          cp -r ../../scripts .
-          cp ../../assets/LICENSE.mkxp-z-with-https.txt .
+      # - name: Prepare archive
+      #   shell: msys2 {0}
+      #   run: |
+      #     mkdir build/artifact
+      #     cd build/artifact
+      #     cp /mingw64/bin/zlib1.dll .
+      #     cp ../../windows/build-mingw64/bin/x64-msvcrt-ruby310.dll .
+      #     cp -r ../../windows/build-mingw64/lib/ruby/3.1.0 .
+      #     mv ./3.1.0 ./stdlib
+      #     cp ../mkxp-z.exe .
+      #     cp ../steam_mkxp-z.exe .
+      #     cp $STEAMWORKS_PATH/redistributable_bin/win64/steam_api64.dll .
+      #     cp ../../mkxp.json .
+      #     cp -r ../../scripts .
+      #     cp ../../assets/LICENSE.mkxp-z-with-https.txt .
 
-      - name: Check for DLLs missing from the artifact
-        shell: msys2 {0}
-        run: |
-          cd build/artifact
-          error_flag=
+      # - name: Check for DLLs missing from the artifact
+      #   shell: msys2 {0}
+      #   run: |
+      #     cd build/artifact
+      #     error_flag=
 
-          for file in *.exe *.dll
-          do
-            ldd_output="$(ldd "$file")"
-            echo "$file"
-            echo "$ldd_output"
+      #     for file in *.exe *.dll
+      #     do
+      #       ldd_output="$(ldd "$file")"
+      #       echo "$file"
+      #       echo "$ldd_output"
 
-            while IFS= read -r line
-            do
-              dll_name="$(echo "$line" | sed -e 's/=>/|/g' | cut -d '|' -f 1 | sed -e 's/^[ \t]*//g' -e 's/[ \t]*$//g')"
-              dll_location="$(echo "$line" | sed -e 's/=>/|/g' | cut -d '|' -f 2 | sed -e 's/^[ \t]*//g' -e 's/[ \t]*$//g')"
-              if [[ "$dll_location" = 'not found'* ]] || [[ "$dll_location" = '/mingw64/bin/'* ]] || [[ "$dll_location" = '/mingw64/lib/'* ]] || [[ "$dll_location" = '/mingw64/usr/bin/'* ]] || [[ "$dll_location" = '/mingw64/usr/lib/'* ]]
-              then
-                error_flag=1
-                echo "::error::$dll_name is missing from the artifact"
-              fi
-            done <<< "$ldd_output"
-          done
+      #       while IFS= read -r line
+      #       do
+      #         dll_name="$(echo "$line" | sed -e 's/=>/|/g' | cut -d '|' -f 1 | sed -e 's/^[ \t]*//g' -e 's/[ \t]*$//g')"
+      #         dll_location="$(echo "$line" | sed -e 's/=>/|/g' | cut -d '|' -f 2 | sed -e 's/^[ \t]*//g' -e 's/[ \t]*$//g')"
+      #         if [[ "$dll_location" = 'not found'* ]] || [[ "$dll_location" = '/mingw64/bin/'* ]] || [[ "$dll_location" = '/mingw64/lib/'* ]] || [[ "$dll_location" = '/mingw64/usr/bin/'* ]] || [[ "$dll_location" = '/mingw64/usr/lib/'* ]]
+      #         then
+      #           error_flag=1
+      #           echo "::error::$dll_name is missing from the artifact"
+      #         fi
+      #       done <<< "$ldd_output"
+      #     done
 
-          if [ -n "$error_flag" ]
-          then
-            exit 1
-          fi
+      #     if [ -n "$error_flag" ]
+      #     then
+      #       exit 1
+      #     fi
 
-      - uses: actions/upload-artifact@v4
-        with:
-          name: mkxp-z.windows.${{github.event_name == 'pull_request' && format('PR{0}', github.event.number) || github.ref_name}}-${{steps.short-sha.outputs.sha}}
-          path: build/artifact
+      # - uses: actions/upload-artifact@v4
+      #   with:
+      #     name: mkxp-z.windows.${{github.event_name == 'pull_request' && format('PR{0}', github.event.number) || github.ref_name}}-${{steps.short-sha.outputs.sha}}
+      #     path: build/artifact
